# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photo Collage Maker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#  pod 'GoogleMobileAdsMediationFacebook'
  pod 'Google-Mobile-Ads-SDK'
  pod 'DRColorPicker'
  pod 'SVProgressHUD'
  pod 'FBAudienceNetwork'
  # Pods for Photo Collage Maker

end
